name: Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android app
        run: ./gradlew app-android:assembleRelease

      - name: Sign Android app
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: app-android/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          output: build/release/signed
          alias: key0
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Build Linux app
        run: ./gradlew app-desktop:packageDeb app-desktop:packageRpm

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            app-android/build/outputs/apk/*/*-signed.apk
            app-desktop/build/compose/binaries/main/*/*.rpm
            app-desktop/build/compose/binaries/main/*/*.deb

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build macOS app
        run: ./gradlew app-desktop:packageDmg

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            app-desktop/build/compose/binaries/main/*/*.dmg

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build Windows app
        run: ./gradlew app-desktop:packageMsi

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            app-desktop/build/compose/binaries/main/*/*.msi
